
version: 2
models:
  - name: athletes
    columns:
      - name: gold_medal_count
        tests:
          - not_null
      - name: silver_medal_count
        tests:
          - not_null
      - name: bronze_medal_count
        tests:
          - not_null
  - name: medals
    columns:
      - name: medal_type
        tests:
          - accepted_values:
              values: ['Gold Medal', 'Silver Medal', 'Bronze Medal']
sources:
  - name: imported_data
    schema: imported_data
    tables:
      - name: athletes
      - name: coaches
      - name: medals
      - name: medals_total
      - name: techincal_officials